### ISSUE TITLE
Workaround GlobalEventHandlers issue

### ISSUE THREAD

**Issue by saschanaz** [saschanaz/bcd-idl-mapper#5]
See https://github.com/mdn/browser-compat-data/issues/17127 and https://github.com/microsoft/TypeScript-DOM-lib-generator/pull/1386#issuecomment-1231651406.

**Comment by Ahmed-Hakeem** [comment]
Should  be solved with your commit: 7e286a2da86ed6e2bd678d34d2bb27ebab71f120

**Comment by saschanaz** [comment]
Ah, forgot to close it. Thank you 👍
